language: php

php:
  - 5.6
  - 7

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader --quiet

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - hackersir-developer@googlegroups.com
    on_success: change
    on_failure: always
